 # Be sure to restart your server when you modify this file.

 # Your secret key is used for verifying the integrity of signed cookies.
 # If you change this key, all old signed cookies will become invalid!

 # Make sure the secret is at least 30 characters and all random,
 # no regular words or you'll be exposed to dictionary attacks.
 # You can use `rake secret` to generate a secure secret key.

 # Make sure the secrets in this file are kept private
 # if you're sharing your code publicly.

 development:
   secret_key_base: 4608faa9d3bd62e1b8e6078d0feb652ff894e91aac47e27a083df2209d48e67662f68059911cd2b487fb4158ea9447147a6feebbb729bce5397fbeeb7738d9fa

 test:
   secret_key_base: b21a378a8737d0e553d884e54b2bd7fffbb99c2a56aea05a5575caf09a62070afce9e4cc5ea8f21ed4746ebcfd34dd907cd2a79e4699b7701fc059550abc773f

 # Do not keep production secrets in the repository,
 # instead read values from the environment.
 production:
   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>